/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clients: Client;
    'journey-tracking': JourneyTracking;
    reports: Report;
    events: Event;
    'analytics-daily': AnalyticsDaily;
    'template-mappings': TemplateMapping;
    'notifications-cache': NotificationsCache;
    campaigns: Campaign;
    'analytics-saved-views': AnalyticsSavedView;
    'analytics-audit-logs': AnalyticsAuditLog;
    'funnel-enrollment': FunnelEnrollment;
    'send-log': SendLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'journey-tracking': JourneyTrackingSelect<false> | JourneyTrackingSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'analytics-daily': AnalyticsDailySelect<false> | AnalyticsDailySelect<true>;
    'template-mappings': TemplateMappingsSelect<false> | TemplateMappingsSelect<true>;
    'notifications-cache': NotificationsCacheSelect<false> | NotificationsCacheSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'analytics-saved-views': AnalyticsSavedViewsSelect<false> | AnalyticsSavedViewsSelect<true>;
    'analytics-audit-logs': AnalyticsAuditLogsSelect<false> | AnalyticsAuditLogsSelect<true>;
    'funnel-enrollment': FunnelEnrollmentSelect<false> | FunnelEnrollmentSelect<true>;
    'send-log': SendLogSelect<false> | SendLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'funnel-config': FunnelConfig;
  };
  globalsSelect: {
    'funnel-config': FunnelConfigSelect<false> | FunnelConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Determines which app the user sees. Sales → Packages, Marketing → Analytics.
   */
  department: 'sales' | 'marketing';
  /**
   * Manager sees everything in their app. Member is scoped (sales members are region-limited).
   */
  level: 'manager' | 'member';
  /**
   * Only used for sales members. Leave empty for managers, marketing, and super-admins.
   */
  regions?: ('Brazil' | 'South Africa' | 'INT' | 'MENA' | 'LATAM' | 'ROW')[] | null;
  superAdmin?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientId: string;
  region: 'Brazil' | 'South Africa' | 'INT' | 'MENA' | 'LATAM' | 'ROW';
  country?: string | null;
  culture?: string | null;
  pkg?: ('Platinum' | 'Gold' | 'Silver' | 'Bronze') | null;
  ams?: string | null;
  status?: ('Active' | 'Converted' | 'Completed' | 'Excluded') | null;
  contacted?: boolean | null;
  deposited?: boolean | null;
  submitted?: string | null;
  converted?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-tracking".
 */
export interface JourneyTracking {
  id: number;
  externalId: string;
  region?: ('Brazil' | 'South Africa' | 'INT' | 'MENA' | 'LATAM' | 'ROW') | null;
  journeyStatus?: ('Active' | 'Converted' | 'Completed' | 'Excluded') | null;
  journeyStartedAt?: string | null;
  journeyEndedAt?: string | null;
  exitReason?: string | null;
  formSubmitted?: boolean | null;
  formSubmittedAt?: string | null;
  path2Step?: string | null;
  path2LastSendAt?: string | null;
  day0SentAt?: string | null;
  path1Step?: string | null;
  path1LastSendAt?: string | null;
  path1ThankyouSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  weekOf: string;
  templateId?: string | null;
  templateName?: string | null;
  region?: ('Brazil' | 'South Africa' | 'INT' | 'MENA' | 'LATAM' | 'ROW') | null;
  msgType?: ('Email' | 'Push') | null;
  sent?: number | null;
  delivered?: number | null;
  delivPct?: number | null;
  opened?: number | null;
  openPct?: number | null;
  clicked?: number | null;
  ctr?: number | null;
  unsub?: number | null;
  unsubPct?: number | null;
  failed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  channel: 'email' | 'push';
  /**
   * Which system produced the event. Email=mailgun (source of truth); push=onesignal_*.
   */
  source: 'mailgun' | 'onesignal_global' | 'onesignal_china';
  eventType:
    | 'accepted'
    | 'delivered'
    | 'opened'
    | 'clicked'
    | 'bounced_hard'
    | 'bounced_soft'
    | 'complained'
    | 'unsubscribed'
    | 'failed';
  /**
   * Email address or push player_id.
   */
  recipient?: string | null;
  /**
   * Mailgun message-id — stable per email, used for dedup.
   */
  messageId?: string | null;
  /**
   * OneSignal notification_id — key to resolve template.
   */
  notificationId?: string | null;
  /**
   * Canonical template key (resolved via TemplateMappings).
   */
  templateKey?: string | null;
  /**
   * Raw per-app template id.
   */
  templateId?: string | null;
  region?: string | null;
  timestamp: string;
  /**
   * First open/click for this recipient+message (for unique-rate math).
   */
  isUnique?: boolean | null;
  /**
   * Raw provider payload snippet (geo, client, etc).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily".
 */
export interface AnalyticsDaily {
  id: number;
  date: string;
  channel: 'email' | 'push';
  source: 'mailgun' | 'onesignal_global' | 'onesignal_china';
  templateKey?: string | null;
  templateName?: string | null;
  region?: string | null;
  sent?: number | null;
  delivered?: number | null;
  uniqueOpens?: number | null;
  totalOpens?: number | null;
  uniqueClicks?: number | null;
  totalClicks?: number | null;
  hardBounces?: number | null;
  softBounces?: number | null;
  complaints?: number | null;
  unsubscribes?: number | null;
  failed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-mappings".
 */
export interface TemplateMapping {
  id: number;
  /**
   * Canonical key, e.g. welcome_bronze.
   */
  templateKey: string;
  templateName: string;
  /**
   * Auto-derived group (prefix before the first " - "). Used for the Family view.
   */
  family?: string | null;
  /**
   * Raw template id in the global OneSignal app.
   */
  globalTemplateId?: string | null;
  /**
   * Raw template id in the China OneSignal app.
   */
  chinaTemplateId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-cache".
 */
export interface NotificationsCache {
  id: number;
  notificationId: string;
  source?: ('onesignal_global' | 'onesignal_china') | null;
  appId?: string | null;
  templateId?: string | null;
  templateKey?: string | null;
  firstSeen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  /**
   * e.g. Q3 Onboarding, Summer Promo.
   */
  name: string;
  description?: string | null;
  /**
   * Internal campaign notes and handoff context.
   */
  notes?: string | null;
  status?: ('draft' | 'active' | 'paused' | 'completed' | 'archived') | null;
  /**
   * Assign one or more templates to this campaign. A template can be in several campaigns.
   */
  templates?: (number | TemplateMapping)[] | null;
  /**
   * Optional hex color for charts, e.g. #075c8f.
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-saved-views".
 */
export interface AnalyticsSavedView {
  id: number;
  name: string;
  owner: number | User;
  visibility?: ('personal' | 'team') | null;
  tab?: string | null;
  days?: number | null;
  campaign?: string | null;
  channel?: string | null;
  region?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-audit-logs".
 */
export interface AnalyticsAuditLog {
  id: number;
  action: 'created' | 'updated' | 'archived' | 'restored' | 'duplicated' | 'deleted' | 'view_saved' | 'view_deleted';
  entityType: string;
  entityId?: string | null;
  entityName?: string | null;
  summary: string;
  actor?: (number | null) | User;
  actorName?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel-enrollment".
 */
export interface FunnelEnrollment {
  id: number;
  /**
   * CRM external_id. Unique -> enrollment idempotency.
   */
  externalId: string;
  /**
   * KYC country (source for region + osApp).
   */
  country?: string | null;
  /**
   * OneSignal Culture tag, e.g. Int-en. Used by step/exclusion rules.
   */
  culture?: string | null;
  language?: string | null;
  /**
   * Which sequence: ROW=16 emails, CNJP=11 (China OR Japan).
   */
  funnelRegion: 'ROW' | 'CNJP';
  /**
   * Which OneSignal app to send from. china ONLY for country===China; Japan uses global.
   */
  osApp: 'global' | 'china';
  /**
   * Sequence-level A/B, assigned once at enrollment. Stable for the whole funnel.
   */
  variant: 'A' | 'B';
  state: 'in_progress' | 'converted' | 'completed';
  currentStep?: string | null;
  lastSentStep?: string | null;
  /**
   * 0-based index of the NEXT send.
   */
  sendIndex: number;
  enrolledAt: string;
  /**
   * When the next send is due. Sender tick selects rows where this <= now.
   */
  nextSendAt?: string | null;
  convertedAt?: string | null;
  /**
   * Last email ACTUALLY sent before conversion.
   */
  convertedAtStep?: string | null;
  completedAt?: string | null;
  paused?: boolean | null;
  excluded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "send-log".
 */
export interface SendLog {
  id: number;
  externalId: string;
  stepId: string;
  variant?: ('A' | 'B') | null;
  /**
   * Which OneSignal app sent it (matches NotificationsCache.source).
   */
  osApp?: ('global' | 'china') | null;
  templateId?: string | null;
  /**
   * OneSignal notification_id — join key to analytics Events.
   */
  notificationId?: string | null;
  attemptedAt: string;
  result: 'sent' | 'skipped_converted' | 'skipped_no_recipient' | 'error';
  errorDetail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'journey-tracking';
        value: number | JourneyTracking;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'analytics-daily';
        value: number | AnalyticsDaily;
      } | null)
    | ({
        relationTo: 'template-mappings';
        value: number | TemplateMapping;
      } | null)
    | ({
        relationTo: 'notifications-cache';
        value: number | NotificationsCache;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'analytics-saved-views';
        value: number | AnalyticsSavedView;
      } | null)
    | ({
        relationTo: 'analytics-audit-logs';
        value: number | AnalyticsAuditLog;
      } | null)
    | ({
        relationTo: 'funnel-enrollment';
        value: number | FunnelEnrollment;
      } | null)
    | ({
        relationTo: 'send-log';
        value: number | SendLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  department?: T;
  level?: T;
  regions?: T;
  superAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientId?: T;
  region?: T;
  country?: T;
  culture?: T;
  pkg?: T;
  ams?: T;
  status?: T;
  contacted?: T;
  deposited?: T;
  submitted?: T;
  converted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-tracking_select".
 */
export interface JourneyTrackingSelect<T extends boolean = true> {
  externalId?: T;
  region?: T;
  journeyStatus?: T;
  journeyStartedAt?: T;
  journeyEndedAt?: T;
  exitReason?: T;
  formSubmitted?: T;
  formSubmittedAt?: T;
  path2Step?: T;
  path2LastSendAt?: T;
  day0SentAt?: T;
  path1Step?: T;
  path1LastSendAt?: T;
  path1ThankyouSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  weekOf?: T;
  templateId?: T;
  templateName?: T;
  region?: T;
  msgType?: T;
  sent?: T;
  delivered?: T;
  delivPct?: T;
  opened?: T;
  openPct?: T;
  clicked?: T;
  ctr?: T;
  unsub?: T;
  unsubPct?: T;
  failed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  channel?: T;
  source?: T;
  eventType?: T;
  recipient?: T;
  messageId?: T;
  notificationId?: T;
  templateKey?: T;
  templateId?: T;
  region?: T;
  timestamp?: T;
  isUnique?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily_select".
 */
export interface AnalyticsDailySelect<T extends boolean = true> {
  date?: T;
  channel?: T;
  source?: T;
  templateKey?: T;
  templateName?: T;
  region?: T;
  sent?: T;
  delivered?: T;
  uniqueOpens?: T;
  totalOpens?: T;
  uniqueClicks?: T;
  totalClicks?: T;
  hardBounces?: T;
  softBounces?: T;
  complaints?: T;
  unsubscribes?: T;
  failed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-mappings_select".
 */
export interface TemplateMappingsSelect<T extends boolean = true> {
  templateKey?: T;
  templateName?: T;
  family?: T;
  globalTemplateId?: T;
  chinaTemplateId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-cache_select".
 */
export interface NotificationsCacheSelect<T extends boolean = true> {
  notificationId?: T;
  source?: T;
  appId?: T;
  templateId?: T;
  templateKey?: T;
  firstSeen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  notes?: T;
  status?: T;
  templates?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-saved-views_select".
 */
export interface AnalyticsSavedViewsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  visibility?: T;
  tab?: T;
  days?: T;
  campaign?: T;
  channel?: T;
  region?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-audit-logs_select".
 */
export interface AnalyticsAuditLogsSelect<T extends boolean = true> {
  action?: T;
  entityType?: T;
  entityId?: T;
  entityName?: T;
  summary?: T;
  actor?: T;
  actorName?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel-enrollment_select".
 */
export interface FunnelEnrollmentSelect<T extends boolean = true> {
  externalId?: T;
  country?: T;
  culture?: T;
  language?: T;
  funnelRegion?: T;
  osApp?: T;
  variant?: T;
  state?: T;
  currentStep?: T;
  lastSentStep?: T;
  sendIndex?: T;
  enrolledAt?: T;
  nextSendAt?: T;
  convertedAt?: T;
  convertedAtStep?: T;
  completedAt?: T;
  paused?: T;
  excluded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "send-log_select".
 */
export interface SendLogSelect<T extends boolean = true> {
  externalId?: T;
  stepId?: T;
  variant?: T;
  osApp?: T;
  templateId?: T;
  notificationId?: T;
  attemptedAt?: T;
  result?: T;
  errorDetail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel-config".
 */
export interface FunnelConfig {
  id: number;
  /**
   * Case-sensitive. Entry requires this STATUS.
   */
  statusRegisteredValue: string;
  /**
   * Case-sensitive. Convenience default for conversion.
   */
  statusActiveValue: string;
  firstDelayHours: number;
  intervalDays: number;
  /**
   * On enrollment, if OneSignal tags are not synced yet, retry this many times before discarding.
   */
  maxTagSyncRetries: number;
  /**
   * Only enroll users registered on/after this date. Protects against back-filling the whole DB. Leave empty to allow all.
   */
  enrollmentCutoffDate?: string | null;
  cnjpCountries?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  chinaCountries?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  oneSignalApps?: {
    globalAppId?: string | null;
    /**
     * n8n credential name for the global REST key.
     */
    globalKeyRef?: string | null;
    chinaAppId?: string | null;
    /**
     * n8n credential name for the china REST key.
     */
    chinaKeyRef?: string | null;
    /**
     * App queried to READ tags/subscriptions at enrollment (usually the global app).
     */
    identityAppId?: string | null;
  };
  sequenceRow?:
    | {
        stepId: string;
        id?: string | null;
      }[]
    | null;
  sequenceCnjp?:
    | {
        stepId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * global UUID for ROW + Japan. china UUID for country===China. A CN step needs both.
   */
  templates?:
    | {
        stepId: string;
        variant: 'A' | 'B';
        global?: string | null;
        china?: string | null;
        id?: string | null;
      }[]
    | null;
  restrictedCountries?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. CycleStatusName equals Crooked. Generic tag rules.
   */
  restrictionRules?:
    | {
        /**
         * How to combine the conditions below.
         */
        match?: ('any' | 'all') | null;
        /**
         * Tag tests against the user's OneSignal tags. Empty rule matches nobody.
         */
        conditions?:
          | {
              /**
               * OneSignal tag, e.g. STATUS, Country, Culture, CycleStatusName, TotalDepositsUSD
               */
              field: string;
              op: 'equals' | 'not_equals' | 'in' | 'not_in' | 'prefix' | 'greater_than' | 'less_than' | 'exists';
              /**
               * For in/not_in use a comma list. Not needed for "exists".
               */
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * User stays in the funnel but skips this step. Replaces the old CN/JP-only list; now works for any country/culture/tag.
   */
  stepRestrictions?:
    | {
        stepId: string;
        /**
         * How to combine the conditions below.
         */
        match?: ('any' | 'all') | null;
        /**
         * Tag tests against the user's OneSignal tags. Empty rule matches nobody.
         */
        conditions?:
          | {
              /**
               * OneSignal tag, e.g. STATUS, Country, Culture, CycleStatusName, TotalDepositsUSD
               */
              field: string;
              op: 'equals' | 'not_equals' | 'in' | 'not_in' | 'prefix' | 'greater_than' | 'less_than' | 'exists';
              /**
               * For in/not_in use a comma list. Not needed for "exists".
               */
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. STATUS equals ACTIVE, OR TotalDepositsUSD greater_than 100. Checked before every send.
   */
  conversionRules?:
    | {
        /**
         * How to combine the conditions below.
         */
        match?: ('any' | 'all') | null;
        /**
         * Tag tests against the user's OneSignal tags. Empty rule matches nobody.
         */
        conditions?:
          | {
              /**
               * OneSignal tag, e.g. STATUS, Country, Culture, CycleStatusName, TotalDepositsUSD
               */
              field: string;
              op: 'equals' | 'not_equals' | 'in' | 'not_in' | 'prefix' | 'greater_than' | 'less_than' | 'exists';
              /**
               * For in/not_in use a comma list. Not needed for "exists".
               */
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funnel-config_select".
 */
export interface FunnelConfigSelect<T extends boolean = true> {
  statusRegisteredValue?: T;
  statusActiveValue?: T;
  firstDelayHours?: T;
  intervalDays?: T;
  maxTagSyncRetries?: T;
  enrollmentCutoffDate?: T;
  cnjpCountries?:
    | T
    | {
        value?: T;
        id?: T;
      };
  chinaCountries?:
    | T
    | {
        value?: T;
        id?: T;
      };
  oneSignalApps?:
    | T
    | {
        globalAppId?: T;
        globalKeyRef?: T;
        chinaAppId?: T;
        chinaKeyRef?: T;
        identityAppId?: T;
      };
  sequenceRow?:
    | T
    | {
        stepId?: T;
        id?: T;
      };
  sequenceCnjp?:
    | T
    | {
        stepId?: T;
        id?: T;
      };
  templates?:
    | T
    | {
        stepId?: T;
        variant?: T;
        global?: T;
        china?: T;
        id?: T;
      };
  restrictedCountries?:
    | T
    | {
        value?: T;
        id?: T;
      };
  restrictionRules?:
    | T
    | {
        match?: T;
        conditions?:
          | T
          | {
              field?: T;
              op?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  stepRestrictions?:
    | T
    | {
        stepId?: T;
        match?: T;
        conditions?:
          | T
          | {
              field?: T;
              op?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  conversionRules?:
    | T
    | {
        match?: T;
        conditions?:
          | T
          | {
              field?: T;
              op?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}